"""
PhishGuard API Key Setup Script
This script helps you configure API keys for external threat intelligence services
"""

import os
import sys

def print_header():
    print("\n" + "="*80)
    print(" PhishGuard - API Key Configuration")
    print("="*80)
    print("\nThis script will help you set up API keys for enhanced phishing detection.")
    print("\nPriority APIs (Highly Recommended):")
    print("  1. Google Safe Browsing - Free, highly accurate phishing detection")
    print("  2. URLScan.io - Free tier available, comprehensive URL analysis")
    print("\nOptional APIs:")
    print("  3. VirusTotal - Free API available, multi-engine malware scanning")
    print("  4. IBM X-Force - Free tier available, threat intelligence")
    print("="*80 + "\n")

def get_api_key(service_name, description, signup_url, is_optional=False):
    """Prompt user for an API key"""
    status = "Optional" if is_optional else "Required"
    print(f"\n{'='*80}")
    print(f"{service_name} [{status}]")
    print(f"{'='*80}")
    print(f"Description: {description}")
    print(f"Sign up at: {signup_url}")
    print()
    
    if is_optional:
        skip = input("Skip this API? (y/n): ").strip().lower()
        if skip == 'y':
            return None
    
    api_key = input(f"Enter your {service_name} API key (or press Enter to skip): ").strip()
    return api_key if api_key else None

def create_env_file(api_keys):
    """Create .env file with API keys"""
    env_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'backend', '.env')
    
    # Read existing .env if it exists
    existing_env = {}
    if os.path.exists(env_path):
        print(f"\nFound existing .env file at: {env_path}")
        overwrite = input("Do you want to update it? (y/n): ").strip().lower()
        if overwrite != 'y':
            print("Setup cancelled.")
            return False
        
        # Read existing values
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    existing_env[key.strip()] = value.strip()
    
    # Merge with new keys
    for key, value in api_keys.items():
        if value:
            existing_env[key] = value
    
    # Write to .env file
    try:
        with open(env_path, 'w') as f:
            f.write("# PhishGuard API Configuration\n")
            f.write("# Generated by setup_api_keys.py\n\n")
            
            f.write("# Priority APIs (Highly Recommended)\n")
            f.write(f"GOOGLE_SAFEBROWSING_API_KEY={existing_env.get('GOOGLE_SAFEBROWSING_API_KEY', '')}\n")
            f.write(f"URLSCAN_API_KEY={existing_env.get('URLSCAN_API_KEY', '')}\n\n")
            
            f.write("# Secondary APIs (Optional)\n")
            f.write(f"VIRUSTOTAL_API_KEY={existing_env.get('VIRUSTOTAL_API_KEY', '')}\n")
            f.write(f"IBM_XFORCE_API_KEY={existing_env.get('IBM_XFORCE_API_KEY', '')}\n")
            f.write(f"IBM_XFORCE_API_PASSWORD={existing_env.get('IBM_XFORCE_API_PASSWORD', '')}\n\n")
            
            f.write("# Legacy APIs\n")
            f.write(f"PHISHTANK_API_KEY={existing_env.get('PHISHTANK_API_KEY', '')}\n")
            f.write(f"CLOUDFLARE_API_KEY={existing_env.get('CLOUDFLARE_API_KEY', '')}\n")
            f.write(f"CLOUDFLARE_EMAIL={existing_env.get('CLOUDFLARE_EMAIL', '')}\n")
        
        print(f"\n✓ API keys saved to: {env_path}")
        return True
    except Exception as e:
        print(f"\n✗ Error saving API keys: {e}")
        return False

def export_to_env_vars(api_keys):
    """Export API keys to environment variables"""
    print("\nExporting to environment variables...")
    for key, value in api_keys.items():
        if value:
            os.environ[key] = value
            print(f"  ✓ {key} set")
    print("\n✓ Environment variables set for current session")

def print_instructions():
    """Print post-setup instructions"""
    print("\n" + "="*80)
    print(" Setup Complete!")
    print("="*80)
    print("\nNext Steps:")
    print("  1. The .env file has been created in the backend directory")
    print("  2. Django will automatically load these API keys when it starts")
    print("  3. Run the application using: python scripts/run_servers.py")
    print("\nAPI Usage Priority:")
    print("  1. Google Safe Browsing (Primary)")
    print("  2. URLScan.io (Primary)")
    print("  3. VirusTotal (Fallback)")
    print("  4. IBM X-Force (Fallback)")
    print("  5. Machine Learning Model (Final fallback)")
    print("\nFor the most accurate detection, we recommend configuring at least")
    print("Google Safe Browsing and URLScan.io API keys.")
    print("="*80 + "\n")

def main():
    print_header()
    
    api_keys = {}
    
    # Priority APIs
    print("\n" + "="*80)
    print(" PRIORITY APIs - Configure these for best results")
    print("="*80)
    
    # Google Safe Browsing
    gsb_key = get_api_key(
        "Google Safe Browsing API",
        "Google's free phishing and malware detection service. Highly accurate and reliable.",
        "https://developers.google.com/safe-browsing/v4/get-started",
        is_optional=False
    )
    if gsb_key:
        api_keys['GOOGLE_SAFEBROWSING_API_KEY'] = gsb_key
    
    # URLScan.io
    urlscan_key = get_api_key(
        "URLScan.io API",
        "Comprehensive URL scanning and analysis service. Free tier available.",
        "https://urlscan.io/user/signup",
        is_optional=False
    )
    if urlscan_key:
        api_keys['URLSCAN_API_KEY'] = urlscan_key
    
    # Optional APIs
    print("\n" + "="*80)
    print(" OPTIONAL APIs - Additional threat intelligence")
    print("="*80)
    
    configure_optional = input("\nConfigure optional APIs? (y/n): ").strip().lower()
    
    if configure_optional == 'y':
        # VirusTotal
        vt_key = get_api_key(
            "VirusTotal API",
            "Multi-engine malware and URL scanning service.",
            "https://www.virustotal.com/gui/join-us",
            is_optional=True
        )
        if vt_key:
            api_keys['VIRUSTOTAL_API_KEY'] = vt_key
        
        # IBM X-Force
        xforce_key = get_api_key(
            "IBM X-Force API Key",
            "IBM's threat intelligence platform.",
            "https://exchange.xforce.ibmcloud.com/settings/api",
            is_optional=True
        )
        if xforce_key:
            api_keys['IBM_XFORCE_API_KEY'] = xforce_key
            xforce_pass = input("Enter IBM X-Force API Password: ").strip()
            if xforce_pass:
                api_keys['IBM_XFORCE_API_PASSWORD'] = xforce_pass
    
    # Save configuration
    if not api_keys:
        print("\n⚠ No API keys configured. The system will rely solely on the ML model.")
        print("This may result in lower accuracy for detecting new phishing sites.")
        proceed = input("\nProceed without API keys? (y/n): ").strip().lower()
        if proceed != 'y':
            print("Setup cancelled.")
            return
    
    if create_env_file(api_keys):
        print_instructions()
        
        # Summary
        print("\nConfigured APIs:")
        if 'GOOGLE_SAFEBROWSING_API_KEY' in api_keys:
            print("  ✓ Google Safe Browsing")
        if 'URLSCAN_API_KEY' in api_keys:
            print("  ✓ URLScan.io")
        if 'VIRUSTOTAL_API_KEY' in api_keys:
            print("  ✓ VirusTotal")
        if 'IBM_XFORCE_API_KEY' in api_keys:
            print("  ✓ IBM X-Force")
        
        if not api_keys:
            print("  ⚠ No APIs configured - ML model only")
        
        print("\n✓ Setup complete! You can now run PhishGuard.")
    else:
        print("\n✗ Setup failed. Please check the error messages above.")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\n✗ Unexpected error: {e}")
        sys.exit(1)





